ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_CONFIRMED = "CONFIRMED"
ORDER_STATUS_CANCELLED = "CANCELLED"

ORDER_STATUS_CHOICES = (
    (ORDER_STATUS_PENDING, "Pending"),
    (ORDER_STATUS_CONFIRMED, "Confirmed"),
    (ORDER_STATUS_CANCELLED, "Cancelled"),
)

