LOW_STOCK_THRESHOLD=10

IN_STOCK="IN_STOCK"
OUT_OF_STOCK="OUT_OF_STOCK"
LOW_STOCK="LOW_STOCK"

STOCK_STATUS_CHOICES = (
    (IN_STOCK, IN_STOCK),
    (OUT_OF_STOCK, OUT_OF_STOCK),
    (LOW_STOCK, LOW_STOCK),
)