from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView


class ListCreateProductsApiView(ListCreateAPIView):...

class RetrieveUpdateDestroyProductApiView(RetrieveUpdateDestroyAPIView):...