ROLE_CUSTOMER = 'CUSTOMER'
ROLE_SALES_USER = 'SALES_USER'
ROLE_ADMIN = 'ADMIN'

USER_ROLE_CHOICES = [
    (ROLE_CUSTOMER, ROLE_CUSTOMER),
    (ROLE_SALES_USER, ROLE_SALES_USER),
    (ROLE_ADMIN, ROLE_ADMIN),
]

