# Generated by Django 5.1.2 on 2025-12-22 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(help_text='Unique product identifier (uppercase alphanumeric, hyphens, underscores)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products_product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=100)),
                ('previous_qty', models.PositiveIntegerField()),
                ('new_qty', models.PositiveIntegerField()),
                ('change_reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_change_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_change_logs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_change_logs', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Change Log',
                'verbose_name_plural': 'Stock Change Logs',
                'db_table': 'products_stock_change_log',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_qty'], name='products_pr_stock_q_d4d3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangelog',
            index=models.Index(fields=['product', '-created_at'], name='products_st_product_611b75_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangelog',
            index=models.Index(fields=['customer'], name='products_st_custome_ebf8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangelog',
            index=models.Index(fields=['created_by'], name='products_st_created_091563_idx'),
        ),
    ]
